name: Python Package Publish

on:
  push:
    branches:
      - indev
  pull_request:
    branches:
      - indev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Configure Git (for bumpversion commit and tag)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install setuptools wheel twine bump2version

      - name: Bump version
        run: bump2version patch  # or 'minor' or 'major'

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - name: Push tag and version commit
        run: |
          git push origin HEAD:indev
          git push origin --tags
